config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'homepage/home'
  get 'homepage/admin_home'
  get '/search' => 'homepage#search', :as => 'search_page'
  post 'homepage/csv_export'
  root 'homepage#home'
  devise_for :clients
  resources :packages, except: [:index]
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :pages, only: [] do
    get 'home', on: :collection
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :authenticate_client!

  def home
    if current_client.org_admin
      redirect_to homepage_admin_home_path
    else
      @packages = Package.where(client_id: current_client.id ).page(params[:page])
    end
  end

  def admin_home
    @operators = Client.where(org_code: current_client.org_code).where.not(email: current_client.email)
    @packages = Package.where(org_code: current_client.org_code ).page(params[:page])

    @total_packages = @packages.length
    @average_price = 0
    @packages.map do |m|
      @average_price = @average_price + m.price
    end
    @average_price = @average_price / @packages.length
    @greatest_distance = @packages.order(:distance)[0]
    @smallest_distance = @packages.order(:distance).reverse[0]

  end

  def search
    @parameter = params[:search].downcase
    @packages = Package.all.where("lower(operator) LIKE :search", search: @parameter).page(params[:page])
  end

  def csv_export
    file = "#{Rails.root}/public/data.csv"
    table = Package.where(org_code: current_client.org_code) # ";0" stops output.  Change "User" to any model.

    CSV.open( file, 'w' ) do |writer|
      writer << table.first.attributes.map { |a,v| a }
      table.each do |s|
        writer << s.attributes.map { |a,v| v }
      end
    end

    Pony.mail(
      to: current_client.email,
      from: 'Route Calculator',
      via: :smtp,
      attachments: {'data.csv' => File.read("#{Rails.root}/public/data.csv")},
      via_options: {
        address: 'smtp.gmail.com',
        port: '587',
        user_name: YOUR_GMAIL_HERE,
        password: YOUR_PASSWORD_HERE,
        authentication: :plain,
        domain: 'mail.google.com'
      },
      subject: 'Test',
      body: 'your csv'
    )
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/_packages_list.html.erb
<table class="sortable">
  <thead>
  <tr>
    <th>Name</th>
    <th>Surname</th>
    <th>Patronymic</th>
    <th>Number</th>
    <th>Email</th>
    <th>Weight</th>
    <th>Lenght</th>
    <th>Width</th>
    <th>Height</th>
    <th>From</th>
    <th>To</th>
    <th>Size</th>
    <th>Price</th>
    <th>Distance</th>
    <th>Created at</th>
    <th>Id</th>


    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @packages.each do |package| %>
    <tr>
      <td><%= package.name %></td>
      <td><%= package.surname %></td>
      <td><%= package.patronymic %></td>
      <td><%= package.number %></td>
      <td><%= package.email%></td>
      <td><%= package.weight %></td>
      <td><%= package.length %></td>
      <td><%= package.width %></td>
      <td><%= package.height %></td>
      <td><%= package.from_addr %></td>
      <td><%= package.to_addr %></td>
      <td><%= package.size %></td>
      <td><%= package.price %></td>
      <td><%= package.distance %></td>
      <td><%= package.created_at %></td>
      <td><%= package.id %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/homepage/admin_home.html.erb
<center>
  <%= link_to "Выйти", destroy_client_session_path, method: :delete %>
  <h3> <%= current_client.email %> </h3>
  <br>
  <%= image_tag(current_client.image.url, alt: 'Image', style: 'max-width:300px;max-height:300px') if current_client.image? %>
  <p> Отфильтровать по оператору </p>
  <%= form_tag(search_page_path, :method => "get") do %>
    <div>
      <%= select_tag(:search, options_from_collection_for_select(@operators, :email, :email)) %>
      <div>
        <br>
        <%= submit_tag "показать"%>
      </div>
    </div>
  <% end %>

  <br>
  <%= link_to 'Сформировать csv таблицу', homepage_csv_export_path, method: :post %>

  <h3>Аналитика</h3>
  <p>Всего заявок <%= @total_packages %></p>
  <% @operators.each do |operator| %>
    <% operators_packages = Package.where(org_code: operator.org_code, operator: operator.email).length %>
    <p>У оператора <%= operator.email %> заявок:<%= operators_packages %> </p>
  <% end %>
  <p>Средняя сумма по заявкам <%= @average_price %></p>
  <p> Самая дальняя посылка - посылка с id <%= @greatest_distance.id %> и ее путь <%= @greatest_distance.distance %></p>
  <p> Самая короткая посылка - посылка с id <%= @smallest_distance.id %> и ее путь <%= @smallest_distance.distance %></p>

  <h2>Текущие заявки</h2>
  <p>(нажмите на заголовок для сортировки)</p>
</center>

<%= page_entries_info @packages %>
<%= paginate @packages %>
<%= render "packages_list" %>

app/views/homepage/csv_export.html.erb
<h1> Письмо с CSV таблицей успешно отправлено на Вашу почту</h1>
<h2> <%= link_to 'назад', homepage_admin_home_path %> </h2>

app/views/homepage/home.html.erb
<center>
  <%= link_to "Выйти", destroy_client_session_path, method: :delete %>

  <h3> <%= current_client.email %> </h3>
  <br>
  <%= link_to "Отправить посылку", new_package_path, style: 'color:blue; font-size:20px'  %>
  <br>
  <br>
  <%= image_tag(current_client.image.url, alt: 'Image', style: 'max-width:300px;max-height:300px') if current_client.image? %>
  <h2>Текущие заявки</h2>
  <p>(нажмите на заголовок для сортировки)</p>
</center>

<%= page_entries_info @packages %>
<%= paginate @packages %>
<%= render "packages_list" %>

app/views/homepage/search.html.erb
<h3>Search Result</h3>

<%= page_entries_info @packages %>
<%= paginate @packages %>
<%= render "packages_list" %>